name: Build Docker Images from Multiple Branches

on:
  push:
    branches:
      - main
      - adservice
      - checkoutservice

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        branch: [adservice, checkoutservice]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: Build and Push Docker Image
        run: |
          cd ${{ matrix.branch }}
          docker buildx build \
            --cache-from=type=registry,ref=khoi2010/ecommerce-app:buildcache \
            --cache-to=type=registry,ref=khoi2010/ecommerce-app:buildcache,mode=max \
            --push -t khoi2010/ecommerce-app:${{ matrix.branch }} .

